[package]
name = "unicode_info"
version = "0.1.0"
edition = "2018"

[lib]
name = "unicode_info"
path = "src/lib.rs"

[[bin]]
name = "generate_js_files"
path = "src/bin/generate_js_files.rs"

[dependencies]
itertools = "0.10"
proc-macro2 = "1.0"
quote = "1.0"
